### ISSUE TITLE
Incompatibility with R 3.2.1

### ISSUE THREAD

**Issue by jackolney** [wrathematics/Rdym#4]
Hi,
The latest build of R is refusing to download / acknowledge 'Rdym'. Are there plans to update it or is there a fundamental difference preventing Rdym from working on the latest build?

Thanks!

**Comment by wrathematics** [comment]
Hi, thanks for the report.

Unfortunately I'm unable to replicate this.  It compiles and loads/works when I use `devtools::install_github()` and when I manually install from source.  Could you give me some more information about what's failing, your platform (Windows/Mac/etc), and the output of `Sys.getenv("LANGUAGE")` from R?

**Comment by jackolney** [comment]
Ah, my mistake! I was installing from CRAN and not directly from github! Sorry, that was silly of me.
Installs and works now with `devtools::install_github("wrathematics/Rdym")`. Thanks for the speedy response though — Great package!

**Comment by wrathematics** [comment]
No worries.  Yeah, I've never submitted this package to CRAN, mostly because I don't enjoy dealing with CRAN's nonsense anymore.

Thanks.
